Bugfix: don't kill the sources when dpkg-buildpackage failed
git-svn-id: file:///home/vog/x/njh/any2deb/trunk@81 7edfa1aa-b5ec-0310-85b9-a344310dd3f3

diff --git a/debuild-cross b/debuild-cross
--- a/debuild-cross
+++ b/debuild-cross
@@ -100,7 +100,12 @@ EOF
 # build Debian packages
 #
 
-dpkg-buildpackage -rfakeroot "$@"
+dpkg-buildpackage -rfakeroot "$@" || {
+    echo "Unable to build the package."
+    echo "Please have a look into: $ARCH-$SOURCE-$VERSION/"
+    echo "and adjust the the patch folder: patch-$ARCH-$SOURCE/"
+    exit 1
+}
 
 
 # clean up
